default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: format
        name: Format
        language: system
        entry: bazel run //:format
        files: .*
