name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      XDG_CACHE_HOME: ~/.cache/bazel-repo
    steps:
      - uses: actions/checkout@v4
      - run: build.sh
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            rules_quickjs-*.tar.gz
            quickjs-*.tar.gz
          body_path: release_notes.md
          fail_on_unmatched_files: true
